Repository sonia-auv/provider_power, pull requests merged in 2022-07, with the labels that each got.

#46 Develop
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
  src/provider_power/provider_power_node.cc
Labels: Priority: Critical, Type: Bug

#49 Fix/debug
  src/provider_power/provider_power_node.cc
Labels: Priority: High, Type: Bug

#50 add flush queue every 30 sec
  src/provider_power/provider_power_node.cc
  src/provider_power/sharedQueue.h
Labels: Priority: High, Type: Feature

#51 changed time btw flush to 15
  src/provider_power/provider_power_node.cc
Labels: Priority: Low, Type: Enhancement

#52 changed get_n_pop_front to get_n_pop_back
  src/provider_power/provider_power_node.cc
  src/provider_power/sharedQueue.h
Labels: Priority: Medium, Type: Bug
