Repository sonia-auv/provider_power, pull requests merged in 2022-05, with the labels that each got.

#26 Feature/auv7
  .github/pull_request_template.md
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
  .gitignore
  CMakeLists.txt
  package.xml
  src/provider_power/provider_power_node.cc
  src/provider_power/provider_power_node.h
  src/provider_power/sharedQueue.h
Labels: Priority: Critical, Type: Feature

#31 Revert "Fix/voltage"
  .github/pull_request_template.md
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
  .gitignore
  CMakeLists.txt
  package.xml
  src/provider_power/provider_power_node.cc
  src/provider_power/provider_power_node.h
  src/provider_power/sharedQueue.h
Labels: Priority: Medium, Type: Feature

#32 changed voltage data size sent to the telemetry
  src/provider_power/provider_power_node.cc
Labels: Priority: Medium, Type: Feature

#35 Fix/voltage
  .github/pull_request_template.md
  .gitignore
  package.xml
  src/provider_power/provider_power_node.cc
  src/provider_power/provider_power_node.h
  src/provider_power/sharedQueue.h
Labels: Priority: Critical, Type: Bug

#36 Add the support for AUV7 for provider_power
  .github/pull_request_template.md
  .github/workflows/docker-image-perception-develop.yml
  .github/workflows/docker-image-perception-feature.yml
  .github/workflows/docker-image-perception-fix.yml
  .gitignore
  package.xml
  src/provider_power/provider_power_node.cc
  src/provider_power/provider_power_node.h
  src/provider_power/sharedQueue.h
Labels: Priority: High, Type: Feature

#37 add temperature cmd
  src/provider_power/provider_power_node.cc
  src/provider_power/provider_power_node.h
Labels: Priority: High, Type: Feature

#38 add space to test an image
  src/provider_power/provider_power_node.cc
Labels: Priority: Critical, Type: Bug
